name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the master branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for the deploy action
      pages: write # Grants permissions for GitHub Pages
      id-token: write # Permissions for OIDC authentication
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or 'dev', 'master' as needed

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: |
          flutter build web --release \
          --base-href="/YOUR_REPO_NAME/" \
          --dart-define=MASTER_FIREBASE_EMAIL=${{ secrets.MASTER_FIREBASE_EMAIL }} \
          --dart-define=MASTER_FIREBASE_PASSWORD=${{ secrets.MASTER_FIREBASE_PASSWORD }}
        # Replace YOUR_REPO_NAME with your actual repository name.
        # This is crucial for correct routing on GitHub Pages URLs.

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web' # The output directory of the flutter build command

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4